#define I2C_DRIVER I2CD0
// the bottom pins of Splinky are connected for the serial pins
#define I2C0_SCL_PIN GP13
#define I2C0_SDA_PIN GP12


#define CIRQUE_PINNACLE_DIAMETER_MM 40
#define CIRQUE_PINNACLE_TAP_ENABLE
#define POINTING_DEVICE_GESTURES_SCROLL_ENABLE
#define CIRQUE_PINNACLE_CURVED_OVERLAY
#define CIRQUE_PINNACLE_SECONDARY_TAP_ENABLE
//#define CIRQUE_PINNACLE_ATTENUATION EXTREG__TRACK_ADCCONFIG__ADC_ATTENUATE_4X
#define POINTING_DEVICE_ROTATION_90
